language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
  - "9"
  - "8"
install:
  - npm i
  - npm run pecker:init
script:
  - npm run pecker:start
after_success:
  # - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
